#!/usr/bin/env node
// Regenerates data/prompts.js from the Markdown source in prompts/.
// Node built-ins only — no dependencies, no `npm install`.
//
// Usage:  node scripts/build.mjs
//
// The Markdown files in prompts/ are the source of truth. data/prompts.js is a
// generated artifact that is committed so the site runs with no build step. If
// Node is unavailable, data/prompts.js can also be edited by hand to mirror the
// Markdown (see README).

import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const PROMPTS_DIR = join(ROOT, "prompts");
const OUT_FILE = join(ROOT, "data", "prompts.js");

// Maps the localized "## " headings used in the Markdown to canonical field keys.
const HEADING_TO_FIELD = {
  // English
  "title": "title",
  "prompt template": "promptTemplate",
  "use case": "useCase",
  "required inputs": "requiredInputs",
  "expected output": "expectedOutput",
  "example": "example",
  // Slovenian
  "naslov": "title",
  "predloga poziva": "promptTemplate",
  "namen uporabe": "useCase",
  "zahtevani vhodni podatki": "requiredInputs",
  "pričakovani rezultat": "expectedOutput",
  "primer": "example",
};

const REQUIRED_FIELDS = [
  "title",
  "promptTemplate",
  "useCase",
  "requiredInputs",
  "expectedOutput",
  "example",
];

function parseFrontMatter(text) {
  const match = text.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!match) return { meta: {}, body: text };
  const meta = {};
  for (const line of match[1].split("\n")) {
    const idx = line.indexOf(":");
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    const value = line.slice(idx + 1).trim();
    meta[key] = value;
  }
  return { meta, body: text.slice(match[0].length) };
}

// Splits a "# EN" / "# SL" body into per-language objects of canonical fields.
function parseBody(body) {
  const langs = {};
  // Split on level-1 headings ("# EN", "# SL").
  const sections = body.split(/^# +/m).filter((s) => s.trim());
  for (const section of sections) {
    const newlineIdx = section.indexOf("\n");
    const langCode = section.slice(0, newlineIdx).trim().toLowerCase();
    if (langCode !== "en" && langCode !== "sl") continue;
    const rest = section.slice(newlineIdx + 1);
    const fields = {};
    // Split on level-2 headings ("## Use case", ...).
    const blocks = rest.split(/^## +/m).filter((b) => b.trim());
    for (const block of blocks) {
      const idx = block.indexOf("\n");
      const heading = block.slice(0, idx).trim().toLowerCase();
      const field = HEADING_TO_FIELD[heading];
      if (!field) continue;
      fields[field] = block.slice(idx + 1).trim();
    }
    langs[langCode] = fields;
  }
  return langs;
}

async function main() {
  const files = (await readdir(PROMPTS_DIR))
    .filter((f) => f.endsWith(".md") && f !== "TEMPLATE.md")
    .sort();

  const prompts = [];
  const warnings = [];

  for (const file of files) {
    const text = await readFile(join(PROMPTS_DIR, file), "utf8");
    const { meta, body } = parseFrontMatter(text);
    const langs = parseBody(body);

    if (!langs.en || !langs.sl) {
      warnings.push(`${file}: missing an EN or SL section — skipped.`);
      continue;
    }
    for (const lang of ["en", "sl"]) {
      for (const field of REQUIRED_FIELDS) {
        if (!langs[lang][field]) {
          warnings.push(`${file} (${lang}): missing field "${field}".`);
        }
      }
    }

    prompts.push({
      id: meta.id || file.replace(/\.md$/, ""),
      order: Number(meta.order) || 0,
      status: meta.status || "draft",
      en: langs.en,
      sl: langs.sl,
    });
  }

  prompts.sort((a, b) => a.order - b.order);

  const header =
    "// AUTO-GENERATED by scripts/build.mjs from the Markdown in prompts/.\n" +
    "// Do not edit by hand unless Node is unavailable (see README).\n" +
    "// Loaded as a <script> so the site works under file:// without fetch().\n\n";
  const out = header + "window.PROMPTS = " + JSON.stringify(prompts, null, 2) + ";\n";
  await writeFile(OUT_FILE, out, "utf8");

  console.log(`Wrote ${prompts.length} prompts to data/prompts.js`);
  if (warnings.length) {
    console.warn("\nWarnings:");
    for (const w of warnings) console.warn("  - " + w);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
